### ISSUE TITLE
Onboarding as Solid veteran

### ISSUE THREAD

**Issue by JollyOrc** [Darcy-Social/shepherd#2]
As a Solid veteran, I sign up to the Darcy Instance using my existing WebID. The system will then let me know in detail which permissions I need to set in order to use this instance. I will then check or set up a public facing username, optionally set a profile picture and can make note of where to add in more information later.

**Comment by promocare** [comment]
Rough estimate 7/10 days
This includes:

- permission detection API
- permission wizard or instructions
- redirect to previously created profile settings page
