### ISSUE TITLE
feed:user profile: Offer using the solid pod profile as shepherd profile

### ISSUE THREAD

**Issue by JollyOrc** [Darcy-Social/shepherd#31]
when setting up Shepherd along with a freshly created Darcypod:
the chosen name and profile picture should be stored in the Solid bio section

When setting up Shepherd with a preexisting Solid pod:
If there is a name and profile picture defined, offer to use these.

**Comment by scenaristeur** [comment]
What does the project become ?

**Comment by JollyOrc** [comment]
sorry for the long waiting time - we have been a bit swamped with other stuff completely outside this project, and the pandemic situation didn't make things easier. @promocare is looking into your commit right now.
