### ISSUE TITLE
feed/user profile: allow editing the solid pod profile directly from Shepherd

### ISSUE THREAD

**Issue by JollyOrc** [Darcy-Social/shepherd#32]
The Darcy profile screen should contain the relevant fields from the Solid profile screen and save changes to the Solid profile.

**Comment by scenaristeur** [comment]
It is better to talk about Profil not in merge request, I think, so 

Hi 👋
So in your mind Shepherd Profil = podProfil with ability to update it ?
Following the solid specs, any app customization like specific shepherd profile properties should be in pref.ttl. I've never use it but is it the way you want to take ?
David

**Comment by JollyOrc** [comment]
yep - although right now, apart from the display / nick name, there aren't any customizations yet.
